'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class empAgregar
    
    '''<summary>
    '''rcbDepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbDepto As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtPaterno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPaterno As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMaterno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaterno As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombre As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCalle As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtnoExterior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnoExterior As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtnoInterior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnoInterior As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtdireccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdireccion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtColonia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColonia As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLocalidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocalidad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtreferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtreferencia As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMunicipio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMunicipio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEstado As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPais As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txttelefono1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttelefono1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txttelefono2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttelefono2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtemail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rxrRFC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rxrRFC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtIMSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIMSS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCurp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNacimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNacimiento As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rcbInfonavit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbInfonavit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtInfoNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInfoNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rcbAguinaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbAguinaldo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAguinaldoNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAguinaldoNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSalario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalario As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtIndice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIndice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtIntegrado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIntegrado As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rcbSexo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbSexo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtBanco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBanco As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtSatRegi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSatRegi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSatContrato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSatContrato As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSatJornada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSatJornada As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtOcupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOcupacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkDeclara control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDeclara As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkasimilado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkasimilado As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkSindicaliado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSindicaliado As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button
End Class
